2024-11-07 20:38:02,820 | INFO | "test_challenge" выполнен успешно
2024-11-07 20:38:02,821 | WARNING | Неверный тип данных для объекта Runner: Имя может быть только строкой, передано int
2024-11-07 20:38:02,823 | WARNING | Traceback (most recent call last):
  File "D:\pythonProgectsForUniversity\LESSONS\tests_12_4.py", line 76, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "D:\pythonProgectsForUniversity\LESSONS\tests_12_4.py", line 16, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-11-07 20:38:02,823 | WARNING | Неверная скорость для Runner: Скорость не может быть отрицательной, сейчас -5
2024-11-07 20:38:02,826 | WARNING | Traceback (most recent call last):
  File "D:\pythonProgectsForUniversity\LESSONS\tests_12_4.py", line 65, in test_walk
    runner = Runner('Вася', -5)
             ^^^^^^^^^^^^^^^^^^
  File "D:\pythonProgectsForUniversity\LESSONS\tests_12_4.py", line 21, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

